[program:xray]
command=/usr/local/bin/xray run -c /home/dev/proxy/xray.json
directory=/workspace
user=dev
autostart=false
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
stopwaitsecs=10
